// Mocks generated by Mockito 5.4.5 from annotations
// in food/test/food/features/auth/presentation/manager/auth_bloc/login/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:food/food/domain/failures/failures.dart' as _i6;
import 'package:food/food/features/auth/data/repositories/auth_repo_impl.dart'
    as _i2;
import 'package:food/food/features/auth/domain/use_cases/auth_usecase.dart'
    as _i4;
import 'package:food/food/features/home/domain/entities/profile.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthRepoImpl_0 extends _i1.SmartFake implements _i2.AuthRepoImpl {
  _FakeAuthRepoImpl_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthUseCase extends _i1.Mock implements _i4.AuthUseCase {
  MockAuthUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthRepoImpl get authRepo => (super.noSuchMethod(
        Invocation.getter(#authRepo),
        returnValue: _FakeAuthRepoImpl_0(
          this,
          Invocation.getter(#authRepo),
        ),
      ) as _i2.AuthRepoImpl);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>> getCurrentUser() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserProfileEntity>(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserProfileEntity>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>> register({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? phoneNumber,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #phoneNumber: phoneNumber,
            #password: password,
          },
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserProfileEntity>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phoneNumber: phoneNumber,
              #password: password,
            },
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> sendEmailVerification(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [email],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #sendEmailVerification,
            [email],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> sendPasswordResetEmail(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #sendPasswordResetEmail,
            [email],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> deleteUserAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserAccount,
          [],
        ),
        returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
            _FakeEither_1<_i6.Failure, void>(
          this,
          Invocation.method(
            #deleteUserAccount,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, void>>);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>> verifyEmail() =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>>.value(
                _FakeEither_1<_i6.Failure, _i7.UserProfileEntity>(
          this,
          Invocation.method(
            #verifyEmail,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, _i7.UserProfileEntity>>);
}
