import 'dart:ui';

const Color kPrimaryColor = Color(0xffFF7622);
const Color kSecondaryColor = Color(0xffFFE1CE);
const Color kContainerColor = Color(0xff98A8B8);
const Color kTextFieldColor = Color(0xffF0F5FA);
const Color kAddressColor = Color(0xff676767);
const Color kTextColorDark = Color(0xff32343E);
const Color kWhiteColor = Color(0xffFFFFFF);
const Color kBlackColor = Color(0xff000000);
const Color kGreyColor = Color(0xffB7C9D9);
const Color kLightGreyColor = Color(0xffF7F9FC);
const Color kScaffoldColorLight = Color(0xffffffff);
const Color kScaffoldColorDark = Color(0xff1E1E2F);
const Color kAuthBgColor = Color(0xff1E1E2E);
const Color kAuthBgColorDark = Color(0xff121223);
const Color kFbColor = Color(0xff395998);
const Color kGoogleColor = Color(0xffDB4437);
const Color kAppleColor = Color(0xff000000);
const Color kTwitterColor = Color(0xff1DA1F2);
const Color kGradientColor1 = Color(0xffE76F00);
const Color kGradientColor2 = Color(0xffFFEB34);
const Color kCloseColor = Color(0xffFFE194);
