// Mocks generated by Mockito 5.4.5 from annotations
// in food/test/food/features/auth/domain/use_cases/auth_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i13;

import 'package:cloud_firestore/cloud_firestore.dart' as _i2;
import 'package:dartz/dartz.dart' as _i11;
import 'package:food/food/domain/failures/failures.dart' as _i14;
import 'package:food/food/features/auth/data/remote/data_sources/delete_user_account_data_source.dart'
    as _i9;
import 'package:food/food/features/auth/data/remote/data_sources/email_verification_data_source.dart'
    as _i5;
import 'package:food/food/features/auth/data/remote/data_sources/email_verification_status_data_source.dart'
    as _i6;
import 'package:food/food/features/auth/data/remote/data_sources/login_data_source.dart'
    as _i3;
import 'package:food/food/features/auth/data/remote/data_sources/password_reset_data_source.dart'
    as _i7;
import 'package:food/food/features/auth/data/remote/data_sources/register_data_source.dart'
    as _i4;
import 'package:food/food/features/auth/data/remote/data_sources/sign_out_data_source.dart'
    as _i8;
import 'package:food/food/features/auth/data/remote/data_sources/user_data_source.dart'
    as _i10;
import 'package:food/food/features/auth/data/repositories/auth_repo_impl.dart'
    as _i12;
import 'package:food/food/features/home/domain/entities/profile.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseFirestore_0 extends _i1.SmartFake
    implements _i2.FirebaseFirestore {
  _FakeFirebaseFirestore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLoginDataSource_1 extends _i1.SmartFake
    implements _i3.LoginDataSource {
  _FakeLoginDataSource_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRegisterDataSource_2 extends _i1.SmartFake
    implements _i4.RegisterDataSource {
  _FakeRegisterDataSource_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmailVerificationDataSource_3 extends _i1.SmartFake
    implements _i5.EmailVerificationDataSource {
  _FakeEmailVerificationDataSource_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmailVerificationStatusDataSource_4 extends _i1.SmartFake
    implements _i6.EmailVerificationStatusDataSource {
  _FakeEmailVerificationStatusDataSource_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePasswordResetDataSource_5 extends _i1.SmartFake
    implements _i7.PasswordResetDataSource {
  _FakePasswordResetDataSource_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignOutDataSource_6 extends _i1.SmartFake
    implements _i8.SignOutDataSource {
  _FakeSignOutDataSource_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteUserAccountDataSource_7 extends _i1.SmartFake
    implements _i9.DeleteUserAccountDataSource {
  _FakeDeleteUserAccountDataSource_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserDataSource_8 extends _i1.SmartFake
    implements _i10.UserDataSource {
  _FakeUserDataSource_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_9<L, R> extends _i1.SmartFake implements _i11.Either<L, R> {
  _FakeEither_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepoImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepoImpl extends _i1.Mock implements _i12.AuthRepoImpl {
  MockAuthRepoImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseFirestore get firebase => (super.noSuchMethod(
        Invocation.getter(#firebase),
        returnValue: _FakeFirebaseFirestore_0(
          this,
          Invocation.getter(#firebase),
        ),
      ) as _i2.FirebaseFirestore);

  @override
  _i3.LoginDataSource get loginService => (super.noSuchMethod(
        Invocation.getter(#loginService),
        returnValue: _FakeLoginDataSource_1(
          this,
          Invocation.getter(#loginService),
        ),
      ) as _i3.LoginDataSource);

  @override
  _i4.RegisterDataSource get registerService => (super.noSuchMethod(
        Invocation.getter(#registerService),
        returnValue: _FakeRegisterDataSource_2(
          this,
          Invocation.getter(#registerService),
        ),
      ) as _i4.RegisterDataSource);

  @override
  _i5.EmailVerificationDataSource get emailVerificationService =>
      (super.noSuchMethod(
        Invocation.getter(#emailVerificationService),
        returnValue: _FakeEmailVerificationDataSource_3(
          this,
          Invocation.getter(#emailVerificationService),
        ),
      ) as _i5.EmailVerificationDataSource);

  @override
  _i6.EmailVerificationStatusDataSource get emailVerificationStatusService =>
      (super.noSuchMethod(
        Invocation.getter(#emailVerificationStatusService),
        returnValue: _FakeEmailVerificationStatusDataSource_4(
          this,
          Invocation.getter(#emailVerificationStatusService),
        ),
      ) as _i6.EmailVerificationStatusDataSource);

  @override
  _i7.PasswordResetDataSource get passwordResetService => (super.noSuchMethod(
        Invocation.getter(#passwordResetService),
        returnValue: _FakePasswordResetDataSource_5(
          this,
          Invocation.getter(#passwordResetService),
        ),
      ) as _i7.PasswordResetDataSource);

  @override
  _i8.SignOutDataSource get signOutService => (super.noSuchMethod(
        Invocation.getter(#signOutService),
        returnValue: _FakeSignOutDataSource_6(
          this,
          Invocation.getter(#signOutService),
        ),
      ) as _i8.SignOutDataSource);

  @override
  _i9.DeleteUserAccountDataSource get deleteAccountService =>
      (super.noSuchMethod(
        Invocation.getter(#deleteAccountService),
        returnValue: _FakeDeleteUserAccountDataSource_7(
          this,
          Invocation.getter(#deleteAccountService),
        ),
      ) as _i9.DeleteUserAccountDataSource);

  @override
  _i10.UserDataSource get userProfileService => (super.noSuchMethod(
        Invocation.getter(#userProfileService),
        returnValue: _FakeUserDataSource_8(
          this,
          Invocation.getter(#userProfileService),
        ),
      ) as _i10.UserDataSource);

  @override
  _i13.Future<_i11.Either<_i14.Failure, void>> deleteUserAccount() =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUserAccount,
          [],
        ),
        returnValue: _i13.Future<_i11.Either<_i14.Failure, void>>.value(
            _FakeEither_9<_i14.Failure, void>(
          this,
          Invocation.method(
            #deleteUserAccount,
            [],
          ),
        )),
      ) as _i13.Future<_i11.Either<_i14.Failure, void>>);

  @override
  _i13.Future<_i11.Either<_i14.Failure, String>> forgotPassword(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [email],
        ),
        returnValue: _i13.Future<_i11.Either<_i14.Failure, String>>.value(
            _FakeEither_9<_i14.Failure, String>(
          this,
          Invocation.method(
            #forgotPassword,
            [email],
          ),
        )),
      ) as _i13.Future<_i11.Either<_i14.Failure, String>>);

  @override
  _i13.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i13.Future<bool>.value(false),
      ) as _i13.Future<bool>);

  @override
  _i13.Future<_i11.Either<_i14.Failure, _i15.UserProfileEntity>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i13
            .Future<_i11.Either<_i14.Failure, _i15.UserProfileEntity>>.value(
            _FakeEither_9<_i14.Failure, _i15.UserProfileEntity>(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i13.Future<_i11.Either<_i14.Failure, _i15.UserProfileEntity>>);

  @override
  _i13.Future<_i11.Either<_i14.Failure, _i15.UserProfileEntity>> register({
    required String? firstName,
    required String? lastName,
    required String? email,
    required String? phoneNumber,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #firstName: firstName,
            #lastName: lastName,
            #email: email,
            #phoneNumber: phoneNumber,
            #password: password,
          },
        ),
        returnValue: _i13
            .Future<_i11.Either<_i14.Failure, _i15.UserProfileEntity>>.value(
            _FakeEither_9<_i14.Failure, _i15.UserProfileEntity>(
          this,
          Invocation.method(
            #register,
            [],
            {
              #firstName: firstName,
              #lastName: lastName,
              #email: email,
              #phoneNumber: phoneNumber,
              #password: password,
            },
          ),
        )),
      ) as _i13.Future<_i11.Either<_i14.Failure, _i15.UserProfileEntity>>);

  @override
  _i13.Future<_i11.Either<_i14.Failure, void>> sendEmailVerification(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [email],
        ),
        returnValue: _i13.Future<_i11.Either<_i14.Failure, void>>.value(
            _FakeEither_9<_i14.Failure, void>(
          this,
          Invocation.method(
            #sendEmailVerification,
            [email],
          ),
        )),
      ) as _i13.Future<_i11.Either<_i14.Failure, void>>);

  @override
  _i13.Future<_i11.Either<_i14.Failure, void>> sendPasswordResetEmail(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i13.Future<_i11.Either<_i14.Failure, void>>.value(
            _FakeEither_9<_i14.Failure, void>(
          this,
          Invocation.method(
            #sendPasswordResetEmail,
            [email],
          ),
        )),
      ) as _i13.Future<_i11.Either<_i14.Failure, void>>);

  @override
  _i13.Future<_i11.Either<_i14.Failure, void>> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i13.Future<_i11.Either<_i14.Failure, void>>.value(
            _FakeEither_9<_i14.Failure, void>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i13.Future<_i11.Either<_i14.Failure, void>>);

  @override
  _i13.Future<_i11.Either<_i14.Failure, _i15.UserProfileEntity>>
      verifyEmail() => (super.noSuchMethod(
            Invocation.method(
              #verifyEmail,
              [],
            ),
            returnValue: _i13.Future<
                    _i11.Either<_i14.Failure, _i15.UserProfileEntity>>.value(
                _FakeEither_9<_i14.Failure, _i15.UserProfileEntity>(
              this,
              Invocation.method(
                #verifyEmail,
                [],
              ),
            )),
          ) as _i13.Future<_i11.Either<_i14.Failure, _i15.UserProfileEntity>>);

  @override
  _i13.Future<_i11.Either<_i14.Failure, _i15.UserProfileEntity>>
      getCurrentUser() => (super.noSuchMethod(
            Invocation.method(
              #getCurrentUser,
              [],
            ),
            returnValue: _i13.Future<
                    _i11.Either<_i14.Failure, _i15.UserProfileEntity>>.value(
                _FakeEither_9<_i14.Failure, _i15.UserProfileEntity>(
              this,
              Invocation.method(
                #getCurrentUser,
                [],
              ),
            )),
          ) as _i13.Future<_i11.Either<_i14.Failure, _i15.UserProfileEntity>>);
}
