// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNP_segNn75ATicBwXwJ3uU3xOd5OHZus',
    appId: '1:522247830688:web:07c8e7212850c88a23ddc5',
    messagingSenderId: '522247830688',
    projectId: 'dfood-5aaf3',
    authDomain: 'dfood-5aaf3.firebaseapp.com',
    storageBucket: 'dfood-5aaf3.firebasestorage.app',
    measurementId: 'G-2JYH55TW5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBywoO46WQTbfFaUOLUWU5ErdmdvN6b05g',
    appId: '1:522247830688:android:c2c72e2f94bc0f5323ddc5',
    messagingSenderId: '522247830688',
    projectId: 'dfood-5aaf3',
    storageBucket: 'dfood-5aaf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMzVm-YAgVruhzppJAUXhZMc-bs3SbMdU',
    appId: '1:522247830688:ios:d4c0cfaac240e1a323ddc5',
    messagingSenderId: '522247830688',
    projectId: 'dfood-5aaf3',
    storageBucket: 'dfood-5aaf3.firebasestorage.app',
    iosBundleId: 'com.sirteefyapps.food',
  );
}
