// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXvIvfpPaXo3xVdngHBs2QNX2VZoxm6uc',
    appId: '1:298577262827:web:5180725cfb4a8d2f7266ae',
    messagingSenderId: '298577262827',
    projectId: 'sirteefy-food',
    authDomain: 'sirteefy-food.firebaseapp.com',
    storageBucket: 'sirteefy-food.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCovd8iU4Qd4rIsx-0jl11zw3iW1uBbFDs',
    appId: '1:298577262827:android:0ce626381f7ebbc97266ae',
    messagingSenderId: '298577262827',
    projectId: 'sirteefy-food',
    storageBucket: 'sirteefy-food.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB76Mx5Zbp8hkE3Qedxnj0BcWJ5zB5YKEA',
    appId: '1:298577262827:ios:f775b26aadce2aba7266ae',
    messagingSenderId: '298577262827',
    projectId: 'sirteefy-food',
    storageBucket: 'sirteefy-food.firebasestorage.app',
    iosBundleId: 'com.sirteefyapps.food',
  );
}
